import Head from "next/head";

export default function Home() {
	return (
		<div className="w-full h-full ">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="w-full h-full prose max-w-none text-center my-[50px]">
				<h1>Water Quality Prediction | Dashboard</h1>
				<div className="flex items-center justify-center my-[50px]">
					{/* value from PH sensor */}
					<div className="stats stats-vertical shadow bg-base-200 m-2 ">
						<div className="stat place-items-center">
							<div className="stat-title"></div>
							<div className="stat-value">PH sensor</div>
							<div className="stat-desc"></div>
						</div>

						<div className="stat place-items-center">
							<div className="stat-value">0</div>
						</div>
					</div>

					{/* solids */}
					<div className="stats stats-vertical shadow bg-base-200 m-2 ">
						<div className="stat place-items-center">
							<div className="stat-value">solids</div>
						</div>

						<div className="stat place-items-center">
							<div className="stat-value">0</div>
						</div>
					</div>

					{/* conductivity */}
					<div className="stats stats-vertical shadow bg-base-200 m-2 ">
						<div className="stat place-items-center">
							<div className="stat-value">conductivity</div>
						</div>

						<div className="stat place-items-center">
							<div className="stat-value">0</div>
						</div>
					</div>

					{/* turbidity */}
					<div className="stats stats-vertical shadow bg-base-200 m-2 ">
						<div className="stat place-items-center">
							<div className="stat-value">turbidity</div>
						</div>

						<div className="stat place-items-center">
							<div className="stat-value">0</div>
						</div>
					</div>
				</div>

				<div className="stats stats-vertical bg-green-400 text-black">
					<div className="stat  ">
						<div className="stat-title text-2xl font-extrabold ">
							Water Quality is Good
						</div>

						<div className="stat-actions">
							<button
								className="btn btn-sm btn-primary"
								onClick={async () => {
									await updateWaterLevel();
								}}
							>
								Refresh
							</button>
						</div>
					</div>
				</div>
			</main>
		</div>
	);
}
